# Generated by Django 3.1.5 on 2021-01-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
            preserve_default=False,
        ),
    ]
