# Generated by Django 3.1.5 on 2021-01-05 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 1, 5)),
            preserve_default=False,
        ),
    ]
