# Generated by Django 3.1.5 on 2021-01-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_family',
            field=models.BooleanField(default=False),
        ),
    ]
